### PR TITLE
Added system overview to documentation, other minor edits

### PR DESCRIPTION
**Pull request by yoid2000**
I think it is helpful to give the user an overview of what is going on. Also, make clear that the *purpose* of dashboards is to create and export anonymized data. All the visualization stuff is a means to that end.

### CODE REVIEW

**Review by edongashi — DISMISSED** [review]
Formatter complains. Do you mind running `npm run format` or `yarn format` if the former does not work?

**Comment by yoid2000** [comment]
I tried both, not sure either worked:

```
PS C:\paul\GitHub\dashboards> npm run format

> DiffixDashboards@1.0.0 format C:\paul\GitHub\dashboards
> prettier --write .

'prettier' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DiffixDashboards@1.0.0 format: `prettier --write .`
npm ERR! Exit status 1
npm ERR! Failed at the DiffixDashboards@1.0.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\local_francis\AppData\Roaming\npm-cache\_logs\2023-02-15T08_23_58_713Z-debug.log
PS C:\paul\GitHub\dashboards> yarn format
yarn run v1.22.11
warning package.json: License should be a valid SPDX license expression
$ prettier --write .
'prettier' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\paul\GitHub\dashboards>
```

**Comment by edongashi** [comment]
Ah, needs an `npm install` first. Ok if I do this and push the branch?

**Comment by yoid2000** [comment]
Ok I did `npm install` and `npm run format` and it seems to have run ok.

How does it look to you?

**Review by edongashi — APPROVED** [review]

**Pull request merged**
